title: Simpleflow .NET
description: A .NET library to build dynamic rules and simple workflows with intuitive script concepts.

remote_theme: just-the-docs/just-the-docs

permalink: pretty

aux_links:
  "Simpleflow on GitHub":
    - "//github.com/navtech-io/Simpleflow"
    

plugins:
  - jekyll-seo-tag
