title: Simpleflow .NET
description: A .NET library and a runtime engine to build dynamic rules and workflows with intuitive and simple Simpleflow scripting language.

remote_theme: just-the-docs/just-the-docs

permalink: pretty

aux_links:
  "Simpleflow on GitHub":
    - "//github.com/navtech-io/Simpleflow"
    

plugins:
  - jekyll-seo-tag
