@startuml HowSimpleflowWorks

skinparam partition {
  BorderColor #dddddd
  BorderThickness 1
  FontColor grey
  RoundCorner 10
}

skinparam component {
  FontSize 15
  FontName Courier
  BorderColor black
  BackgroundColor white
  ArrowFontName Impact
  ArrowColor #1d3ddb
}
: Input (Script, Argument)/
: Determine cache key of the given script: \n Determine cache key based on hash value of the script \n or with the user supplied cache id;

if (Is the function \navilable in cache?) then (yes)
  :Get the function from cache;
else (no)
partition "   Compile \n& Cache" {
 : Parse;
  : Generate IL code;
  note right: Uses\nFunction\nRegister
  
  : Compile as a function\n with an input parameter;
  : Store generated function in cache;
}
endif


:Execute the function (with given argument);
:Output/

@enduml    