@startuml Simpleflow

skinparam linetype ortho

skinparam component {
  FontSize 15
  
  FontName Courier
  BorderColor black
  BackgroundColor white
  ArrowFontName Impact
  ArrowColor #db691d
}

skinparam package {
  FontSize 13
  FontName Courier
  BorderColor white
  BackgroundColor #fadd93
  ArrowFontName Impact
  
}

package "Default Execution Pipeline"  {
    Script -right- [Cache Component]
    [Cache Component] -right-> [Parser Component]  
    [Cache Component] -right-> [Execution Component]  
    [Parser Component] -right-> [Execution Component] 

    [Execution Component] - Output
}
@enduml    