//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Navtech\Opensource\Simpleflow\src\Simpleflow\Parser\Grammar\SimpleflowParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Simpleflow.Parser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SimpleflowParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
internal interface ISimpleflowParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] SimpleflowParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.letStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetStmt([NotNull] SimpleflowParser.LetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.ruleStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleStmt([NotNull] SimpleflowParser.RuleStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.generalStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneralStatement([NotNull] SimpleflowParser.GeneralStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.endRuleStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndRuleStmt([NotNull] SimpleflowParser.EndRuleStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.setStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetStmt([NotNull] SimpleflowParser.SetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.messageStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageStmt([NotNull] SimpleflowParser.MessageStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.errorStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitErrorStmt([NotNull] SimpleflowParser.ErrorStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.outputStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutputStmt([NotNull] SimpleflowParser.OutputStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.functionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionStmt([NotNull] SimpleflowParser.FunctionStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.exitStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExitStmt([NotNull] SimpleflowParser.ExitStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.messageText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageText([NotNull] SimpleflowParser.MessageTextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] SimpleflowParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.templateStringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateStringLiteral([NotNull] SimpleflowParser.TemplateStringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.templateStringAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateStringAtom([NotNull] SimpleflowParser.TemplateStringAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.arithmeticExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmeticExpression([NotNull] SimpleflowParser.ArithmeticExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] SimpleflowParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] SimpleflowParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.functionParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionParameter([NotNull] SimpleflowParser.FunctionParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.functionParameterValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionParameterValue([NotNull] SimpleflowParser.FunctionParameterValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.objectIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectIdentifier([NotNull] SimpleflowParser.ObjectIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.identifierIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierIndex([NotNull] SimpleflowParser.IdentifierIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex([NotNull] SimpleflowParser.IndexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.indexNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexNumber([NotNull] SimpleflowParser.IndexNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLiteral([NotNull] SimpleflowParser.StringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.numberLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberLiteral([NotNull] SimpleflowParser.NumberLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.boolLeteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolLeteral([NotNull] SimpleflowParser.BoolLeteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.noneLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoneLiteral([NotNull] SimpleflowParser.NoneLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.arrayLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayLiteral([NotNull] SimpleflowParser.ArrayLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.arrayValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayValue([NotNull] SimpleflowParser.ArrayValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.jsonObj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonObj([NotNull] SimpleflowParser.JsonObjContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPair([NotNull] SimpleflowParser.PairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicate([NotNull] SimpleflowParser.PredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.testExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTestExpression([NotNull] SimpleflowParser.TestExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.logicalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOperator([NotNull] SimpleflowParser.LogicalOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalOperator([NotNull] SimpleflowParser.RelationalOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperand([NotNull] SimpleflowParser.OperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.unaryOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOperand([NotNull] SimpleflowParser.UnaryOperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimpleflowParser.eos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEos([NotNull] SimpleflowParser.EosContext context);
}
} // namespace Simpleflow.Parser
