//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simpleflow.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simpleflow.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&apos;partial&apos; keyword can only be used with JSON object to update properties.&quot;.
        /// </summary>
        internal static string InvalidPartialKeywordUsage {
            get {
                return ResourceManager.GetString("InvalidPartialKeywordUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide static method only. It does not support non-static method..
        /// </summary>
        internal static string RegisterNonStaticMethodError {
            get {
                return ResourceManager.GetString("RegisterNonStaticMethodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable name &apos;{0}&apos; is a reserved word, cannot be used for variable name..
        /// </summary>
        internal static string ReservedWordException {
            get {
                return ResourceManager.GetString("ReservedWordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any one of the service cannot be null in array of services..
        /// </summary>
        internal static string ServiceCannotBeNull {
            get {
                return ResourceManager.GetString("ServiceCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type mismatch. Please choose a different name instead of using existing variable with a different type.
        /// </summary>
        internal static string TypeMismatchWithExistingVar {
            get {
                return ResourceManager.GetString("TypeMismatchWithExistingVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A variable named &apos;{0}&apos; is already defined..
        /// </summary>
        internal static string VariableAlreadyDefined {
            get {
                return ResourceManager.GetString("VariableAlreadyDefined", resourceCulture);
            }
        }
    }
}
