name: publish

on:
 release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version:  | 
            3.1.x
            5.0.x
            6.0.x
    - name: Test
      run: ./build.cmd Test --Configuration Release
    - name: pack
      run: ./build.cmd Pack --Configuration Release
    - name: Publish
      run: ./build.cmd Publish 
      env:
        NuGetApiKey: ${{ secrets.NUGET_API_KEY }}
